### ISSUE TITLE
Add tests to CI for Windows (and maybe others)

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#117]
Since Windows handles filepaths differently (and probably some other things I'm not thinking of), we should also configure the GitHub Actions testing to run on a Windows VM -- if that's doable within GitHub Actions. Should also look into whether to do the same for e.g. MacOS and/or others.

**Comment by CatalinStratu** [comment]
@swinslow , I can try to handle this issue!

**Comment by swinslow** [comment]
That's great -- thank you @CatalinStratu!

**Comment by CatalinStratu** [comment]
Thanks, I'll take care of this task after I'm done with task #120

**Comment by CatalinStratu** [comment]
It will be necessary to refactor some unit tests. To be able to make all the tests run well on both Linux and Windows
![image](https://user-images.githubusercontent.com/28156781/161084556-349afd8a-6816-42c4-880b-2b523ce39de8.png)

**Comment by swinslow** [comment]
Thanks @CatalinStratu. If there are some tests that need refactoring, that makes sense and that's fine to include in a proposed PR.

I'd suggest breaking up refactoring changes into small separate PRs wherever possible so that they can be discussed one by one, rather than one very large PR which would be harder to evaluate.

On the specific failures from your screenshot, note that the verification code and number of Files should be the same regardless of whether the Golang tools are being run on Windows or on Linux. The fact that they're different here is a good thing; that means that the tests are identifying a problem with the tools-golang that is leading to different results on the different platforms. We should dig into why the results are different, and figure out how to fix the bug in the tools -- rather than changing the tests to hide the bug  :)

For this particular test, it looks like this is where the `builder` package is creating an SPDX document by analyzing a test folder. This particular test folder, [`testdata/project1`](https://github.com/spdx/tools-golang/tree/main/testdata/project1), contains a symbolic link file. I'd be willing to bet that's why you're seeing different results on Windows vs. Linux, since (as far as I know) Windows doesn't have a symbolic link concept.

Can you submit a separate issue for this particular test error, so that we can dig into that specifically? Resolving that bug is going to take a bit of digging to see how symbolic links are handled for other SPDX tools, and it's a bit separate from this issue #117 for enabling the Windows tests to run within the GitHub Actions CI system. Thank you!

**Comment by swinslow** [comment]
Oh, I forgot to mention -- in case you're wondering what this verification code thingy is, [section 7.9 of the SPDX spec](https://spdx.github.io/spdx-spec/package-information/#79-package-verification-code-field) has more details.

**Comment by CatalinStratu** [comment]
@swinslow  https://github.com/golang/go/issues/39183

**Comment by CatalinStratu** [comment]
@swinslow  The solution proposed by me can be found in this PR https://github.com/spdx/tools-golang/pull/129

**Comment by kzantow** [comment]
Hiya, @swinslow -- a user submitted a [PR with a fix for Windows](https://github.com/spdx/tools-golang/pull/241), so I thought I'd look into getting the [tests running on Windows](https://github.com/spdx/tools-golang/pull/242). As expected, there are some path separator (and other) issues, but I'm not entirely sure the "right" thing to do here. I don't use any of this functionality, so I really don't want to make changes that would break things for people, but I see a couple of issues:
1. if I scan a directory on Unix and the same directory on Windows, I get different packages/files/etc. because of the path separators
2. path excludes are OS-dependent

To me, I would expect scanning the same set of files on either file system would result in the _exact_ same packages, which tells me that we should be normalizing these to Unix paths. This would also lean into supporting unix paths for exclude patterns on both OSes (and possibly _also_ allowing Windows-style exclude paths). But again, I've not used any of these functions, and would like some guidance what people think is the right thing to do here.
