### ISSUE TITLE
tvloader: Error when Snippet does not immediately follow its File section

### ISSUE THREAD

**Issue by CatalinStratu** [spdx/tools-golang#124]
When two identical files are inserted, the error below appears. 
![image](https://user-images.githubusercontent.com/28156781/160440763-92b4da6e-4923-4bb6-96bf-09d3a6de5250.png)

The file that I used when I identified this error is: [https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXTagExample-v2.2.spdx](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXTagExample-v2.2.spdx)

I want to mention that the SnippetSPDXID tag is in both files.

**Comment by swinslow** [comment]
Thanks for filing this @CatalinStratu -- I'm taking a look now to see whether this is an issue with the example / sample document, or with the tvloader parser.

As mentioned [here](https://github.com/spdx/tools-golang/pull/123#discussion_r839067848), note though that I think the files being compared in this example are not actually identical. That shouldn't cause the parsing issue here, but just flagging to avoid confusion.

**Comment by swinslow** [comment]
OK -- so it looks like this is a parsing error in tvloader, due to an ambiguity in the SPDX spec. See https://github.com/spdx/spdx-spec/issues/651 for more details.

Basically, one possible reading of the spec says that, for tag-value files, a Snippet section should always come immediately after the File section that "contains" it. But a different reading is just that the Snippet needs to be _somewhere_ after the corresponding File, even if it's not immediately after it.

The current tvloader code takes the first reading, and because of that it assumes that a `SnippetSPDXID` tag will only appear when it's in the middle of parsing a File section. So in the sample file at `examples/sample-docs/tv/SPDXTagExample-v2.2.spdx`, it hits a parsing failure when it encounters the `SnippetSPDXID` tag coming after a Package section.

We'll need to see how https://github.com/spdx/spdx-spec/issues/651 is resolved before we can address this here. That means we'll kick this down the road to 0.4.0.

In the meantime, for the 0.3.0 release I'm going to add another different sample document, so that example 6 can be run without erroring out.

**Comment by CatalinStratu** [comment]
@swinslow I would like to work on this issue, can you give me some suggestions on where I can look for the problem? Thanks!

**Comment by CatalinStratu** [comment]
Hi @swinslow, this problem was solved by @ianling in the PR #133

**Comment by CatalinStratu** [comment]
This problem was solved in the PR #133
