### ISSUE TITLE
Nil ptr deref panic when parsing JSON SBOM with a null relationships value

### ISSUE THREAD

**Issue by nchelluri** [spdx/tools-golang#238]
If I try to parse [spdx-null-rel.json](https://github.com/spdx/tools-golang/files/15112659/spdx-null-rel.json) - a JSON SBOM containing a `null` value in the `relationships` array, then I get a panic. I am using `tools-golang` v0.5.4.

**Comment by kzantow** [comment]
Hi @nchelluri I would just note that this does not look like it's a valid SPDX document -- instead of [the required object](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/schemas/spdx-schema.json#L692), it has a `null` value for a relationship entry (rather than a `null` `relationships` array):
```
"relationships": [
  null
],
```
That said, the library shouldn't panic. Thanks for reporting!

**Comment by nchelluri** [comment]
I definitely agree that the `null` value is invalid. I just happened to accidentally hack up an SBOM file in such a way that this happened. I was just testing some stuff out. (My main aim here is to say I am not writing an SBOM generator that generates invalid SPDX SBOMs)
