### ISSUE TITLE
[Optional Upgrade] Checksum Struct

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/tools-golang#49]
Checksums are currently stored in coalesced strings. They can be upgraded to use a struct.

Following seems like a suitable implementation:
```go
type Checksum {
    Algorithm, Value String
}
```
For now, the Algorithm field is kept as a String.

We can also make it a field that allows only algorithms defined by the model in an enum.
Implementation goes as follows:
```golang
type ChecksumAlgorithm int
const (
    MD5 ChecksumAlgorithm = iota
    SHA1
    SHA512
    MD2
    // other algorithms...
)

type Checksum {
    Algorithm ChecksumAlgorithm
    Value String
}
```

**Comment by swinslow** [comment]
+1 from me, thanks @RishabhBhatnagar. I like this as an approach, including the enum for algorithms. A list of the particular algorithms recognized in SPDX 2.2 can be found in [section 3.10.4](https://spdx.github.io/spdx-spec/3-package-information/#310-package-checksum).

Shifting in this direction would also enable having a single common utility function to parse algorithm:value checksum strings into this structure -- instead of rewriting it for each tag-value field where one of these appears.

**Comment by RishabhBhatnagar** [comment]
I'm sorry to raise this issue. When I was re-iterating the existing issues. 
I found an issue filed by you which proposes the same changes with different intention and field names for the Checksum struct.
The issue: #41 .

@swinslow, let me know which names will you be more comfortable with.

There are two options: {ChecksumAlgorithm, Value} or {ChecksumType, Value}.

**Comment by specter25** [comment]
https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXRdfExample-v2.2.spdx.rdf.xml#L21
https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.2.spdx.json#L69

@RishabhBhatnagar , @swinslow various specs use the word "algorithm" to specify the algoritm used . So i think using  this {ChecksumAlgorithm, Value} format would be better . 
Moreover , i am willing to work on this issue , so can i start ?
