### ISSUE TITLE
rdfloader: Issue With The Licenses

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/tools-golang#55]
Licenses, when associated with itself, will cause infinite recursion in the tool.

Licenses are implemented without using pointers. Hence, everytime a new License object is created.
It is not possible to cache it. As, everytime a new object will be created and adding data to it won't affect the old one causing inconsistency of data.

@swinslow , Is it possible for any spdx document to have cyclic dependency on licenses?
Only way I can see that happening is via a `ConjunctiveLicenseSet` or `DisjunctiveLicenseSet`.

@swinslow, should I assume that there might be a case where a license is associated with itself in some way?

**Comment by swinslow** [comment]
(cc @goneall in case he has different thoughts here)

Hi @RishabhBhatnagar, my expectation is that there should never be a cyclical reference in a license. The reason I say that is because every license in RDF format should (in theory) also be expressible in a corresponding string that is a "license expression". [Appendix IV of the SPDX spec](https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/) has more details about license expressions.

Tag-value files use the string-format license expressions. If an RDF file somehow had a cyclical reference in a license, I assume it would generate an infinite recursion and would not be expressible as a string, so it would not be translatable to a tag-value format.

I'm sure there's probably a simpler or more precise explanation, but that's what I'm going with. 😀

**Comment by goneall** [comment]
In practice, there shouldn't be any cyclic relationships but it is technically possible in the model since there is no restriction on license sets.

Since it is technically possible, we should check for cyclic references and flag them as an error.  BTW - the same issue is in the Java tools - we're not checking for cyclic references there either.
